### ISSUE TITLE
Suggestion for topic "Recovery after snapshot"

### ISSUE THREAD

**Issue by brunoamancio** [Noc2/Chiota#2]
I suggest you use a great idea used in Carriota, but adapted to this context. Please read "2. Ledger Pages" from https://medium.com/deviota/carriota-romeo-ultra-light-ledger-2b525aa5be71

**Comment by Noc2** [comment]
Thanks for the link. I already read it. It’s a great article. It might be a good idea to switch the address for chatting after a certain number of messages on this address (similar to the pages in this article) (to improve loading and for additional security), but with the NTRU encryption you don’t have to do it for every message, like with MAM and it would still be quantum secure.
A recovery of the messages after a snapshot is in theory already possible (not yet implemented), since the encrypted tryteStrings are currently stored locally for performance reasons. So, as long as you don’t delete your app at the same moment as the snapshot happens you can upload your messages after the snapshot again. The only problem might be that it probably would take quite some time and you need to come to a consensus with your chat partner.
